const types = {
  // get notes
  START_GET_NOTES: 'START_GET_NOTES',
  SUCCESS_GET_NOTES: 'SUCCESS_GET_NOTES',
  ERROR_GET_NOTES: 'ERROR_GET_NOTES',

  // create note
  START_CREATE_NOTE: 'START_CREATE_NOTE',
  SUCCESS_CREATE_NOTE: 'SUCCESS_CREATE_NOTE',
  ERROR_CREATE_NOTE: 'ERROR_CREATE_NOTE',

  // delete note
  START_DELETE_NOTE: 'START_DELETE_NOTE',
  SUCCESS_DELETE_NOTE: 'SUCCESS_DELETE_NOTE',
  ERROR_DELETE_NOTE: 'ERROR_DELETE_NOTE',
};

export default types;
