const types = {
  START_REGISTER: 'START_REGISTER',
  SUCCESS_REGISTER: 'SUCCESS_REGISTER',
  ERROR_REGISTER: 'ERROR_REGISTER',

  START_LOGIN: 'START_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  ERROR_LOGIN: 'ERROR_LOGIN',

  START_LOGOUT: 'START_LOGOUT',
  SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
  ERROR_LOGOUT: 'ERROR_LOGOUT',
};

export default types;
